### ISSUE TITLE
Can't delete temp directory

### ISSUE THREAD

**Issue by lord-ne** [berndpfrommer/ubuntu_server_installer_mod#1]
I can't delete the temporary working directory (e.g. `sudo rm -rf ~/temp`) after the script completes. I get errors `rm: cannot remove '/home/noam/temp/orig_disk/.disk/base_installable': Read-only file system` for many files.

I am running on WSL, Ubuntu 22.04

**Comment by lord-ne** [comment]
Solved: Just need to reboot

**Comment by berndpfrommer** [comment]
Bug in script: did not unmount iso file system. Fixed with [this commit](https://github.com/berndpfrommer/ubuntu_server_installer_mod/commit/2588d04ffb3bd5e4ce36354f683f3f52a0c1ca84)
